# Generated by Django 2.0.5 on 2019-03-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('product_description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='categories.Category')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': 'upc',
            },
        ),
    ]
